name: get_practice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  get: 4.6.5
  flutter: 
    sdk: flutter
  widgets: 
    path: ./widgets
  fluent_ui: ^3.12.0
  flutter_staggered_animations: ^1.1.1
  usb_serial: ^0.4.0
  quick_usb: ^0.4.0
  libserialport: ^0.2.0+3
  flutter_libserialport: ^0.2.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

